### ISSUE TITLE
ide有很多这样的错误提示

### ISSUE THREAD

**Issue by Godlike-Yu** [DragonKnightOfBreeze/Paradox-Language-Support#105]
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#26,DefaultDispatcher-worker-5,5,main] 870273150 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#53,AWT-EventQueue-0,6,main] 711953684
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:921)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:197)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTreeOrFileElement(PsiFileImpl.java:708)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:645)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:33)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:346)
	at icu.windea.pls.script.psi.ParadoxScriptPsiAccessorsKt.getGreenStub(ParadoxScriptPsiAccessors.kt:48)
	at icu.windea.pls.lang.util.ParadoxDefinitionManager.getInfo(ParadoxDefinitionManager.kt:36)
	at icu.windea.pls.lang._extensionsKt.getDefinitionInfo(_extensions.kt:196)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.getPropertyDoc(ParadoxDocumentationTarget.kt:143)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.computeLocalDocumentation(ParadoxDocumentationTarget.kt:78)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.access$computeLocalDocumentation(ParadoxDocumentationTarget.kt:1)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invokeSuspend(ParadoxDocumentationTarget.kt:60)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:40)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.backend.documentation.impl.ImplKt.computeDocumentation(impl.kt:30)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:41)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:104)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:28)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:56)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:213)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
	at kotlinx.coroutines.flow.internal.FlowValueWrapperInternalKt.emitInternal(FlowValueWrapperInternal.kt:39)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:23)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:21)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by DragonKnightOfBreeze** [comment]
这玩意如果真要一个个修复的话简直是一场噩梦

**Comment by DragonKnightOfBreeze** [comment]
这类报错可以忽略，方法：`doubel shift` -> `registry` -> `slow.operations`

把过滤得到的选项全部取消勾选

**Comment by Godlike-Yu** [comment]
好的 感谢解答 我是完全不懂代码（只会用大佬的插件搞搞mod） 所以看到有提示错误就全复制过来了 感觉好像不太影响继续用 不过确实是在更新完插件版本之后出现的

**Comment by kaiser-chris** [comment]
Hi fyi I also get these exceptions.

Plugin Version: 1.3.25

The error happens when I hover over this error:
![image](https://github.com/user-attachments/assets/99a7da60-81d4-4b63-861e-2fe5d2ca50a1)

And there are a lot of exceptions in a short time. All about `read access.`

Here are two more stacktraces:
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#402,DefaultDispatcher-worker-66,5,main] 541218136 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#62,AWT-EventQueue-0,6,main] 901388279
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:921)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:814)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:367)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:177)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:58)
	at icu.windea.pls.lang.search.ParadoxLocalisationSearcher.doProcessAllElements(ParadoxLocalisationSearcher.kt:56)
	at icu.windea.pls.lang.search.ParadoxLocalisationSearcher.processQuery(ParadoxLocalisationSearcher.kt:22)
	at icu.windea.pls.lang.search.ParadoxLocalisationSearcher.processQuery(ParadoxLocalisationSearcher.kt:15)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at icu.windea.pls.lang.search.ParadoxQuery.find(ParadoxQuery.kt:25)
	at icu.windea.pls.config.expression.CwtLocalisationLocationExpressionImpl.resolve(CwtLocalisationLocationExpression.kt:113)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.addRelatedLocalisationsForDefinition(ParadoxDocumentationTarget.kt:515)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.buildDefinitionDefinition(ParadoxDocumentationTarget.kt:442)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.getDefinitionDoc(ParadoxDocumentationTarget.kt:157)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.getPropertyDoc(ParadoxDocumentationTarget.kt:144)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.computeLocalDocumentation(ParadoxDocumentationTarget.kt:78)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.access$computeLocalDocumentation(ParadoxDocumentationTarget.kt:1)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invokeSuspend(ParadoxDocumentationTarget.kt:60)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:40)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.backend.documentation.impl.ImplKt.computeDocumentation(impl.kt:30)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:41)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:104)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:28)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:56)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:213)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
	at kotlinx.coroutines.flow.internal.FlowValueWrapperInternalKt.emitInternal(FlowValueWrapperInternal.kt:39)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:23)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:21)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

````
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#402,DefaultDispatcher-worker-66,5,main] 541218136 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#62,AWT-EventQueue-0,6,main] 901388279
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:921)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:157)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:98)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:267)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.isInContent(WorkspaceFileIndexImpl.kt:86)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:211)
	at icu.windea.pls.lang.search.scope.ParadoxSearchScope$Companion.fromFile(ParadoxSearchScope.kt:40)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector$defaultScope$2.invoke(ChainedParadoxSelector.kt:32)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector$defaultScope$2.invoke(ChainedParadoxSelector.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector.getDefaultScope(ChainedParadoxSelector.kt:31)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector$scope$2.invoke(ChainedParadoxSelector.kt:37)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector$scope$2.invoke(ChainedParadoxSelector.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at icu.windea.pls.lang.search.selector.ChainedParadoxSelector.getScope(ChainedParadoxSelector.kt:34)
	at icu.windea.pls.lang.search.ParadoxLocalisationSearcher.processQuery(ParadoxLocalisationSearcher.kt:18)
	at icu.windea.pls.lang.search.ParadoxLocalisationSearcher.processQuery(ParadoxLocalisationSearcher.kt:15)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at icu.windea.pls.lang.search.ParadoxQuery.find(ParadoxQuery.kt:25)
	at icu.windea.pls.config.expression.CwtLocalisationLocationExpressionImpl.resolve(CwtLocalisationLocationExpression.kt:113)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.addRelatedLocalisationsForDefinition(ParadoxDocumentationTarget.kt:515)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.buildDefinitionDefinition(ParadoxDocumentationTarget.kt:442)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.getDefinitionDoc(ParadoxDocumentationTarget.kt:157)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.getPropertyDoc(ParadoxDocumentationTarget.kt:144)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.computeLocalDocumentation(ParadoxDocumentationTarget.kt:78)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTargetKt.access$computeLocalDocumentation(ParadoxDocumentationTarget.kt:1)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invokeSuspend(ParadoxDocumentationTarget.kt:60)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at icu.windea.pls.lang.documentation.ParadoxDocumentationTarget$computeDocumentation$1.invoke(ParadoxDocumentationTarget.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:40)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.backend.documentation.impl.ImplKt.computeDocumentation(impl.kt:30)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:41)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:104)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:28)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:56)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:213)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
	at kotlinx.coroutines.flow.internal.FlowValueWrapperInternalKt.emitInternal(FlowValueWrapperInternal.kt:39)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:23)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:21)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by kaiser-chris** [comment]
After I disabled inspection for this `conflicting configs` error in the Victoria 3 files I do not get any further exceptions.

Hope this helps.

**Comment by kaiser-chris** [comment]
Since using 1.3.26 I have not had any more exceptions.

At least for Victoria 3 this should be fixed.
