### ISSUE TITLE
NullPointerException when opening project

### ISSUE THREAD

**Issue by matshou** [DragonKnightOfBreeze/Paradox-Language-Support#2]
```
java.lang.NullPointerException
	at icu.windea.pls.PlsExtensionsKt.getConfig(PlsExtensions.kt:36)
	at icu.windea.pls.core.ParadoxFileTypeOverrider.getOverriddenFileType(ParadoxFileTypeOverrider.kt:32)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$getFileTypeByFile$13(FileTypeManagerImpl.java:601)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:54)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:601)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:595)
	at org.jetbrains.kotlin.scripting.definitions.DefinitionsKt.isKotlinFileType(definitions.kt:66)
	at org.jetbrains.kotlin.scripting.definitions.DefinitionsKt.isNonScript(definitions.kt:60)
	at org.jetbrains.kotlin.idea.core.script.configuration.listener.DefaultScriptChangeListener.isApplicable(DefaultScriptChangeListener.kt:23)
	at org.jetbrains.kotlin.idea.core.script.configuration.listener.ScriptChangesNotifier.getListener(ScriptChangesNotifier.kt:98)
	at org.jetbrains.kotlin.idea.core.script.configuration.listener.ScriptChangesNotifier.access$getListener(ScriptChangesNotifier.kt:25)
	at org.jetbrains.kotlin.idea.core.script.configuration.listener.ScriptChangesNotifier$listenForChangesInScripts$1.runScriptDependenciesUpdateIfNeeded$lambda-1(ScriptChangesNotifier.kt:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by DragonKnightOfBreeze** [comment]
Can the plugin be applied and used normally after  NPE？

**Comment by yooksi** [comment]
Everything seems to work fine now. This exception occurred as I was renaming and moving around descriptor files.
