### ISSUE TITLE
Intellij freezes while editing inline scripts

### ISSUE THREAD

**Issue by LubieKakao1212** [DragonKnightOfBreeze/Paradox-Language-Support#59]
Intellij freezes on launch or when pasting peaces of code

This may be related since it mentions the file I am editing
```
SEVERE - #c.i.u.ExecutorsQuery - Recursive load of: is@stellaris:0#0#eos_dispatch_alignment_events
event_target:eos_leader
java.lang.IllegalStateException: Recursive load of: is@stellaris:0#0#eos_dispatch_alignment_events
event_target:eos_leader
	at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
	at com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2208)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2198)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4933)
	at icu.windea.pls.core.util.CancelableCache.get(Caches.kt:33)
	at icu.windea.pls.config.config.CwtConfigContext.getConfigs(CwtConfigContext.kt:46)
	at icu.windea.pls.lang.CwtConfigHandler.doGetConfigs(CwtConfigHandler.kt:357)
	at icu.windea.pls.lang.CwtConfigHandler.getConfigs(CwtConfigHandler.kt:316)
	at icu.windea.pls.lang.CwtConfigHandler.getConfigs$default(CwtConfigHandler.kt:304)
	at icu.windea.pls.script.references.ParadoxScriptExpressionReferenceProvider.getReferencesByElement(ParadoxScriptExpressionReferenceProvider.kt:32)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:32)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
	at com.intellij.psi.PsiReferenceService.getContributedReferences(PsiReferenceService.java:33)
	at icu.windea.pls.script.psi.impl.ParadoxScriptPsiImplUtil.getReferences(ParadoxScriptPsiImplUtil.kt:862)
	at icu.windea.pls.script.psi.impl.ParadoxScriptPropertyKeyImpl.getReferences(ParadoxScriptPropertyKeyImpl.java:100)
	at icu.windea.pls.lang.index.ParadoxValueSetValueIndexSupport.indexScriptElement(ParadoxExpressionIndexSupports.Core.kt:60)
	at icu.windea.pls.core.index.ParadoxExpressionIndex$indexDataForScriptFile$1.visitElement(ParadoxExpressionIndex.kt:54)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at icu.windea.pls.script.psi.impl.ParadoxScriptPropertyKeyImpl.accept(ParadoxScriptPropertyKeyImpl.java:34)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:53)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:10)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:42)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:34)
	at icu.windea.pls.core.index.ParadoxExpressionIndex$indexDataForScriptFile$1.visitElement(ParadoxExpressionIndex.kt:81)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at icu.windea.pls.script.psi.impl.ParadoxScriptRootBlockImpl.accept(ParadoxScriptRootBlockImpl.java:30)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:748)
	at icu.windea.pls.core.index.ParadoxExpressionIndex.indexDataForScriptFile(ParadoxExpressionIndex.kt:51)
	at icu.windea.pls.core.index.ParadoxExpressionIndex.indexData(ParadoxExpressionIndex.kt:41)
	at icu.windea.pls.core.index.ParadoxFileBasedIndex.buildFileData(ParadoxFileBasedIndex.kt:86)
	at icu.windea.pls.core.index.ParadoxFileBasedIndex.access$buildFileData(ParadoxFileBasedIndex.kt:13)
	at icu.windea.pls.core.index.ParadoxFileBasedIndex$gist$2.invoke$lambda$0(ParadoxFileBasedIndex.kt:78)
	at com.intellij.util.gist.VirtualFileGistOverGistStorage.getOrCalculateAndCache(VirtualFileGistOverGistStorage.java:76)
	at com.intellij.util.gist.VirtualFileGistOverGistStorage.getFileData(VirtualFileGistOverGistStorage.java:37)
	at icu.windea.pls.core.index.ParadoxFileBasedIndex.getFileData(ParadoxFileBasedIndex.kt:105)
	at icu.windea.pls.core.index.ParadoxExpressionIndex.getFileData(ParadoxExpressionIndex.kt:172)
	at icu.windea.pls.core.search.ParadoxInlineScriptUsageSearcher.processQuery$lambda$1(ParadoxInlineScriptUsageSearcher.kt:34)
	at com.intellij.psi.search.FileTypeIndex.processFiles(FileTypeIndex.java:55)
	at icu.windea.pls.core.search.ParadoxInlineScriptUsageSearcher.doProcessFiles(ParadoxInlineScriptUsageSearcher.kt:48)
	at icu.windea.pls.core.search.ParadoxInlineScriptUsageSearcher.processQuery(ParadoxInlineScriptUsageSearcher.kt:29)
	at icu.windea.pls.core.search.ParadoxInlineScriptUsageSearcher.processQuery(ParadoxInlineScriptUsageSearcher.kt:19)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at icu.windea.pls.core.search.ParadoxQuery.forEach(ParadoxQuery.kt:81)
	at icu.windea.pls.lang.config.CwtInlineScriptConfigContextProvider.getConfigs(CwtConfigContextProviders.kt:352)
	at icu.windea.pls.config.config.CwtConfigContext.doGetConfigs(CwtConfigContext.kt:60)
	at icu.windea.pls.config.config.CwtConfigContext.getConfigs$lambda$0(CwtConfigContext.kt:47)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4938)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4933)
	at icu.windea.pls.core.util.CancelableCache.get(Caches.kt:33)
	at icu.windea.pls.config.config.CwtConfigContext.getConfigs(CwtConfigContext.kt:46)
	at icu.windea.pls.lang.config.CwtInlineScriptConfigContextProvider.getConfigs(CwtConfigContextProviders.kt:184)
	at icu.windea.pls.config.config.CwtConfigContext.doGetConfigs(CwtConfigContext.kt:60)
	at icu.windea.pls.config.config.CwtConfigContext.getConfigs$lambda$0(CwtConfigContext.kt:47)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4938)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4933)
	at icu.windea.pls.core.util.CancelableCache.get(Caches.kt:33)
	at icu.windea.pls.config.config.CwtConfigContext.getConfigs(CwtConfigContext.kt:46)
	at icu.windea.pls.lang.CwtConfigHandler.doGetConfigs(CwtConfigHandler.kt:357)
	at icu.windea.pls.lang.CwtConfigHandler.getConfigs(CwtConfigHandler.kt:316)
	at icu.windea.pls.lang.CwtConfigHandler.getConfigs$default(CwtConfigHandler.kt:304)
	at icu.windea.pls.core.editor.folding.ParadoxExpressionFoldingBuilder$buildFoldRegions$1.visitProperty(ParadoxExpressionFoldingBuilder.kt:40)
	at icu.windea.pls.core.editor.folding.ParadoxExpressionFoldingBuilder$buildFoldRegions$1.visitElement(ParadoxExpressionFoldingBuilder.kt:35)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at icu.windea.pls.script.psi.impl.ParadoxScriptPropertyImpl.accept(ParadoxScriptPropertyImpl.java:38)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:53)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:10)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:42)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:34)
	at icu.windea.pls.core.editor.folding.ParadoxExpressionFoldingBuilder$buildFoldRegions$1.visitElement(ParadoxExpressionFoldingBuilder.kt:36)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at icu.windea.pls.script.psi.impl.ParadoxScriptRootBlockImpl.accept(ParadoxScriptRootBlockImpl.java:30)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:748)
	at icu.windea.pls.core.editor.folding.ParadoxExpressionFoldingBuilder.buildFoldRegions(ParadoxExpressionFoldingBuilder.kt:33)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:90)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:40)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:90)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:72)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:272)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:240)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:89)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:73)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:267)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:253)
	at com.intellij.codeInsight.folding.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:49)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by DragonKnightOfBreeze** [comment]
Not sure if it can be guaranteed that it has been repaired, urther verification is required
